# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rescue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rescue.proto',
  package='rescue',
  syntax='proto3',
  serialized_options=b'\n\013rescueserviceB\020rescue2ServiceImplP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nrescue.proto\x12\x04\x66ire\"\"\n\x12\x63ontactRescueRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1d\n\x0c\x66ireResponse\x12\r\n\x05value\x18\x01 \x01(\t\"P\n\rRescueEmergency\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06injury\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\"\"\n\x12\x66ireResponseStream\x12\x0c\n\x04text\x18\x01 \x01(\t2\x85\x01\n\x04\x66ire\x12;\n\x0b\x63ontactRescue\x12\x18.rescue.contactRescueRequest\x1a\x12.rescue.rescueResponse\x12@\n\remergencyRescue\x12\x13.rescue.rescueEmergency\x1a\x18.rescue.rescueResponseStream0\x01\x42!\n\x0b\x66ireserviceB\x10\x66ire2ServiceImplP\x01\x62\x06proto3'
)




_CONTACTRESCUEREQUEST = _descriptor.Descriptor(
  name='contactRescueRequest',
  full_name='rescue.contactRescueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='rescue.contactRescueRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_RESCUERESPONSE = _descriptor.Descriptor(
  name='rescueResponse',
  full_name='rescue.rescueResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='rescue.rescueResponse.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_RESCUEEMERGENCY = _descriptor.Descriptor(
  name='rescueEmergency',
  full_name='rescue.rescueEmergency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rescue.rescueEmergency.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='injury', full_name='rescue.rescueEmergency.injury', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='rescue.rescueEmergency.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='rescue.rescueEmergency.priority', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=167,
)


_RESCUERESPONSESTREAM = _descriptor.Descriptor(
  name='rescueResponseStream',
  full_name='rescue.rescueResponseStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='rescue.rescueResponseStream.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=203,
)

DESCRIPTOR.message_types_by_name['contactRescueRequest'] = _CONTACTRESCUEREQUEST
DESCRIPTOR.message_types_by_name['rescueResponse'] = _RESCUERESPONSE
DESCRIPTOR.message_types_by_name['rescueEmergency'] = _RESCUEEMERGENCY
DESCRIPTOR.message_types_by_name['rescueResponseStream'] = _RESCUERESPONSESTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

contactRescueRequest = _reflection.GeneratedProtocolMessageType('contactRescueRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTACTRESCUEREQUEST,
  '__module__' : 'rescue_pb2'
  # @@protoc_insertion_point(class_scope:rescue.contactRescueRequest)
  })
_sym_db.RegisterMessage(contactRescueRequest)

rescueResponse = _reflection.GeneratedProtocolMessageType('rescueResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESCUERESPONSE,
  '__module__' : 'rescue_pb2'
  # @@protoc_insertion_point(class_scope:rescue.rescueResponse)
  })
_sym_db.RegisterMessage(rescueResponse)

rescueEmergency = _reflection.GeneratedProtocolMessageType('rescueEmergency', (_message.Message,), {
  'DESCRIPTOR' : _RESCUEEMERGENCY,
  '__module__' : 'rescue_pb2'
  # @@protoc_insertion_point(class_scope:rescue.rescueEmergency)
  })
_sym_db.RegisterMessage(rescueEmergency)

rescueResponseStream = _reflection.GeneratedProtocolMessageType('rescueResponseStream', (_message.Message,), {
  'DESCRIPTOR' : _RESCUERESPONSESTREAM,
  '__module__' : 'rescue_pb2'
  # @@protoc_insertion_point(class_scope:rescue.rescueResponseStream)
  })
_sym_db.RegisterMessage(rescueResponseStream)


DESCRIPTOR._options = None

_RESCUE = _descriptor.ServiceDescriptor(
  name='rescue',
  full_name='rescue.rescue',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=206,
  serialized_end=339,
  methods=[
  _descriptor.MethodDescriptor(
    name='contactRescue',
    full_name='rescue.rescue.contactRescue',
    index=0,
    containing_service=None,
    input_type=_CONTACTRESCUEREQUEST,
    output_type=_RESCUERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='emergencyRescue',
    full_name='rescue.rescue.emergencyRescue',
    index=1,
    containing_service=None,
    input_type=_RESCUEEMERGENCY,
    output_type=_RESCUERESPONSESTREAM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESCUE)

DESCRIPTOR.services_by_name['rescue'] = _RESCUE

# @@protoc_insertion_point(module_scope)
