# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rescue_pb2 as rescue__pb2


class rescueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.contactRescue = channel.unary_unary(
                '/rescue.rescue/contactRescue',
                request_serializer=rescue__pb2.contactRescueRequest.SerializeToString,
                response_deserializer=rescue__pb2.rescueResponse.FromString,
                )
        self.emergencyRescue = channel.unary_stream(
                '/rescue.rescue/emergencyRescue',
                request_serializer=rescue__pb2.rescueEmergency.SerializeToString,
                response_deserializer=rescue__pb2.rescueResponseStream.FromString,
                )


class rescueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def contactRescue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def emergencyRescue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rescueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'contactRescue': grpc.unary_unary_rpc_method_handler(
                    servicer.contactRescue,
                    request_deserializer=rescue__pb2.contactRescueRequest.FromString,
                    response_serializer=rescue__pb2.rescueResponse.SerializeToString,
            ),
            'emergencyRescue': grpc.unary_stream_rpc_method_handler(
                    servicer.emergencyRescue,
                    request_deserializer=rescue__pb2.rescueEmergency.FromString,
                    response_serializer=rescue__pb2.rescueResponseStream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rescue.rescue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rescue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def contactrescue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rescue.rescue/contactRescue',
            rescue__pb2.contactRescueRequest.SerializeToString,
            rescue__pb2.rescueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def emergencyRescue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rescue.rescue/emergencyRescue',
            rescue__pb2.rescueEmergency.SerializeToString,
            rescue__pb2.rescueResponseStream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
